services:
  redis:
    image: redis:latest
    container_name: redis
    restart: always
    ports:
      - "6379:6379"
    volumes:
      - "c:/Users/AMIT SINGH/Desktop/redis-caching/redis-data:/root/redis"
      - "c:/Users/AMIT SINGH/Desktop/redis-caching/redis.conf:/usr/local/etc/redis/redis.conf"
    environment:
      - REDIS_PASSWORD=redis1234
      - REDIS_PORT=6379
      - REDIS_DATABASES=16
